### ISSUE TITLE
provenance

### ISSUE THREAD

**Issue by valentinedwv** [CINERGI/Foundry#1]
Burak to generate provenance response from Mongo, Tom to display it
Need to test in all browsers (currently problems in IE)

**Comment by bozyurt** [comment]
Provenance web service is available for testing at route

http://132.249.238.151:8080/foundry/api/cinergi/prov/doc

Below is an example

http://132.249.238.151:8080/foundry/api/cinergi/prov/doc?id=http://www.czo.arizona.edu/data/pub/valle/MetStation/met1_daily/data_daily_met1_metadata.hdr
